# Generated by Django 3.1.6 on 2021-04-04 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_feeding'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeding',
            name='art',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.art'),
            preserve_default=False,
        ),
    ]
