# Generated by Django 3.1.6 on 2021-04-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_feeding_art'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='art',
            name='locations',
            field=models.ManyToManyField(to='main_app.Location'),
        ),
    ]
